### ISSUE TITLE
Incorporate information about conventions and best practices

### ISSUE THREAD

**Issue by edufschmidt** [snt-arg/guidelines#2]
Below are a few suggestions:

### IDE
- [VSCode](https://code.visualstudio.com/)

### Git
- [GitKraken](https://www.gitkraken.com/)
- [General](https://deepsource.io/blog/git-best-practices/)
- [Commit guidelines](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53)

### ROS
- [Official best practices](http://wiki.ros.org/ROS/Patterns/Conventions)
- [Best practices from ETH](https://github.com/leggedrobotics/ros_best_practices/wiki)
### Python
- [Pep8](https://www.python.org/dev/peps/pep-0008/)
- [Linting](https://code.visualstudio.com/docs/languages/python)

### C++
- [Google Styleguide](https://google.github.io/styleguide/cppguide.html)
- [Bjarne Stroustrup's core guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#S-introduction)
- [Linting](https://code.visualstudio.com/docs/languages/cpp) 

### Docker
- [Best practices](https://docs.docker.com/develop/dev-best-practices/)
- [Dockerfile best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

**Comment by hridaybavle** [comment]
Thank you @edufschmidt, but since the guidelines are for all of us, feel free to edit it yourself and then add me as a reviewer if you feel necessary. You can add this directly to the repo if you want.

**Comment by edufschmidt** [comment]
Closing this issue as all suggestions have been implemented in #3
